apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: <P_NAME>
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: <P_NAME>
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: <P_NAME>
          image: <IMAGE_TAG>
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 2000m
              memory: 4096Mi
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 7106
---
apiVersion: v1
kind: Service
metadata:
  name: <P_NAME>-service
spec:
  type: NodePort
  ports:
    - port: 7106
      nodePort: 37106
  selector:
    name: <P_NAME>
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: <P_NAME>-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite /mb/search/(.*) /$1 break;
spec:
  rules:
    - host: gomk.io
      http:
        paths:
          - path: /mb/search
            backend:
              serviceName: <P_NAME>-service
              servicePort: 7023
