server:
  port: 10010
  
elasticsearch:
  #ip: 39.105.192.98:29200
  ip: 10.212.169.154:9200,10.212.169.162:9200,10.212.169.157:9200
  #elasticsearch.ip=192.168.85.133:9200,192.168.85.133:9400,192.168.85.135:9200,192.168.85.135:9400
  index:
    zbName: zg_zhaobiao #招标文件
    zgyqName: zg_zgyq #资格要求
    jsyqName: zg_jsyq #技术要求
    pbbfName: zg_pbbf #评标办法
    zjName: zg_zaojia #造价成果
    tbName: zg_toubiao #投标文件 
    zcfgName: zg_zcfg #政策法规文件 
    zbfbName: zg_zbfb #招标范本文件 
    completionName: zg_completion #搜索补全
  shards: 3
  replicas: 2
  analyzer: ik_smart
  
    
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      id-type: auto
      db-type: mysql
    banner: false
    # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: io.gomk.enums
  type-aliases-package: io.gomk.model.entity
    
spring:
  application:
    name: gomk-b-core
  datasource:
    druid:
      min-idle: 10  
      test-while-idle: true
      max-active: 20
      initial-size: 5
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-wait: 10
      url: jdbc:mysql://10.212.169.142:3306/analysis?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&serverTimezone=UTC&useSSL=false
      username: zg
      password: ZGmysql123!
    url: jdbc:mysql://39.105.192.98:33306/bidata?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: Abcd1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    hbase:
#      quorum: xxx
#      rootDir: xxx
#      nodeParent: xxx

swagger:
   host: 
   
hdfs.path: hdfs://localhost:9000
hdfs.username: root