server:
  port: 10010
  
elasticsearch:
  #ip: 39.105.192.98:29200
  ip: 10.212.169.154:9200,10.212.169.162:9200,10.212.169.157:9200
  #elasticsearch.ip=192.168.85.133:9200,192.168.85.133:9400,192.168.85.135:9200,192.168.85.135:9400
  index:
    zbName: zg_zhaobiao #招标文件
    zgyqName: zg_zgyq #资格要求
    jsyqName: zg_jsyq #技术要求
    pbbfName: zg_pbbf #评标办法
    zjName: zg_zaojia #造价成果
    tbName: zg_toubiao #投标文件 
    zcfgName: zg_zcfg #政策法规文件 
    zbfbName: zg_zbfb #招标范本文件 
    completionName: zg_completion #搜索补全
  shards: 3
  replicas: 2
  analyzer: ik_smart
  
    
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      id-type: auto
      db-type: mysql
    banner: false
    # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: io.gomk.enums
  type-aliases-package: io.gomk.model.entity

spring:
  autoconfigure.exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.212.169.142:3306/BIData?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&serverTimezone=UTC&useSSL=false
          username: zg
          password: ZGmysql123!
        oneself:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.212.169.142:3306/analysis?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&serverTimezone=UTC&useSSL=false
          username: zg
          password: ZGmysql123!
  data:
    hbase:
      master: 10.212.169.158:60000
      zookeeper:
        quorum: 10.212.169.158,10.212.169.166,10.212.169.167
        port: 2181
        znode: /hbase-unsecure
        maxsize: 1572864000   
  redis:
    host: 10.212.169.159
    port: 7001
    password: GCGSredis123!
    timeout: 1000
    lettuce:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
             
swagger:
   host: 
   
hdfs.path: hdfs://localhost:9000
hdfs.username: root