server:
  port: 10010
  servlet:
    context-path: /dac
cas:
  server-url-prefix: https://test-gcgsibs3-2-11:8443/cas
  server-login-url: https://test-gcgsibs3-2-11:8443/cas/login
  client-host-url: http://10.212.169.159:10010/dac
  
cookie:
  domain: 39.105.18.142
  
util:
  idcardtool:
    path: http://127.0.0.1:10011
    
elasticsearch:
  #ip: 39.105.192.98:29200
  ip: 10.212.169.154:9200,10.212.169.162:9200,10.212.169.157:9200
  #elasticsearch.ip=192.168.85.133:9200,192.168.85.133:9400,192.168.85.135:9200,192.168.85.135:9400
  index:
    zbName: zg_zhaobiao #招标文件
    zgyqName: zg_zgyq #资格要求
    jsyqName: zg_jsyq #技术要求
    pbbfName: zg_pbbf #评标办法
    zjName: zg_zaojia #造价成果
    tbName: zg_toubiao #投标文件 
    zcfgName: zg_zcfg #政策法规文件 
    zbfbName: zg_zbfb #招标范本文件 
    completionName: zg_completion #搜索补全
  shards: 3
  replicas: 2
  analyzer: ik_smart
  
graph:
  query:
    TimeLimit: 8000
    fastProperty: true
  storage:
    backend: cql
    keyspace: graph_1102
    hostname: 127.0.0.1
    batchLoading: true
  search:
    backend: elasticsearch
    hostname: 10.212.169.154:9200
  cache:
    enable: true
    #秒
    time: 300
    size: 0.25
  
    
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      id-type: auto
      db-type: mysql
    banner: false
    # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: io.gomk.enums
  type-aliases-package: io.gomk.model.entity

spring:
  autoconfigure.exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.212.169.142:3306/BIData?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&serverTimezone=UTC&useSSL=false
          username: zg
          password: ZGmysql123!
        oneself:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.212.169.142:3306/analysis?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&serverTimezone=UTC&useSSL=false
          username: zg
          password: ZGmysql123!
  data:
    hbase:
      master: 10.212.169.158:60000
      tableName: FileStore
      columnName: a 
      zookeeper:
        quorum: 10.212.169.158,10.212.169.166,10.212.169.167
        port: 2181
        znode: /hbase-unsecure
        maxsize: 1572864000  
    hdfs:
      server: hdfs://10.212.169.158:8020
      zbfbDst: /ibs/zbfb/
  redis:
      password: GCGSredis123! #密码 默认为空
      timeout: 6000 #连接超时时常（毫秒）
      cluster:
        #测试环境
        nodes: 10.212.169.159:7001,10.212.169.159:7002,10.212.169.142:7001,10.212.169.142:7002,10.212.169.168:7001,10.212.169.168:7002
      jedis:
        pool:
          max-active: 1000 #连接池最大连接数（负值表示没限制）
          max-wait: -1 #连接池最大阻塞等待时间（负值表示没限制）
          max-idle: 10 #连接池中最大空闲连接
          min-idle: 5 #连接池中最小空闲连接        
             
swagger:
   host: 
 