server:
  port: 10010
  
cookie:
  domain: 39.105.18.142
  
util:
  idcardtool:
    path: http://58.119.224.26:8080

elasticsearch:
  #ip: 39.105.192.98:29200
  ip: 58.119.224.27:29200
  #elasticsearch.ip=192.168.85.133:9200,192.168.85.133:9400,192.168.85.135:9200,192.168.85.135:9400
  index:
    zbName: index_zhaobiao_test #招标文件
    zgyqName: index_zgyq_test #资格要求
    jsyqName: index_jsyq_test #技术要求
    pbbfName: index_pbbf_test #评标办法
    zjName: index_zaojia_test #造价成果
    tbName: index_toubiao_test #投标文件 
    zcfgName: index_zcfg_test #政策法规文件 
    zbfbName: index_zbfb_test #招标范本文件 
    completionName: index_completion_test #搜索补全
  shards: 2
  replicas: 1
  analyzer: hanlp
  
    
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      id-type: auto
      db-type: mysql
    banner: false
    # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: io.gomk.enums
  type-aliases-package: io.gomk.model.entity

graph:
  query:
    TimeLimit: 8000
    fastProperty: true
  storage:
    backend: cql
    keyspace: graph_1102
    hostname: 101.201.77.122
    batchLoading: true
  search:
    backend: elasticsearch
    hostname: 58.119.224.27:29200
  cache:
    enable: true
    #秒
    time: 300
    size: 0.25

spring:
  autoconfigure.exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://39.105.192.98:33306/bidata?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&serverTimezone=UTC&useSSL=false
          username: root
          password: Abcd1234!
        oneself:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://39.105.192.98:33306/t_g_parse_info?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&serverTimezone=UTC&useSSL=false
          username: root
          password: Abcd1234!

  data:
    hbase:
      master: 10.212.169.158:60000
      zookeeper:
        quorum: 10.212.169.158,10.212.169.166,10.212.169.167
        port: 2181
        znode: /hbase-unsecure
        maxsize: 1572864000
    hdfs:
      server: hdfs://10.212.169.158:8020
      zbfbDst: /ibs/zbfb/
      tableName: FileStore
      columnName: a
  redis:
      password: GCGSredis123! #密码 默认为空
      timeout: 6000 #连接超时时常（毫秒）
      cluster:
        #测试环境
        nodes: 10.212.169.159:7001,10.212.169.159:7002,10.212.169.142:7001,10.212.169.142:7002,10.212.169.168:7001,10.212.169.168:7002
      jedis:
        pool:
          max-active: 1000 #连接池最大连接数（负值表示没限制）
          max-wait: -1 #连接池最大阻塞等待时间（负值表示没限制）
          max-idle: 10 #连接池中最大空闲连接
          min-idle: 5 #连接池中最小空闲连接        
 
swagger:
   host: 
   