server:
  port: 7106

elasticsearch:
  #ip: 39.105.192.98:29200
  ip: 58.119.224.27:29200
  #elasticsearch.ip=192.168.85.133:9200,192.168.85.133:9400,192.168.85.135:9200,192.168.85.135:9400
  index:
    zbName: index_zhaobiao_test #招标文件
    zgyqName: index_zgyq_test #资格要求
    jsyqName: index_jsyq_test #技术要求
    pbbfName: index_pbbf_test #评标办法
    zjName: index_zaojia_test #造价成果
    tbName: index_toubiao_test #投标文件 
    zcfgName: index_zcfg_test #政策法规文件 
    zbfbName: index_zbfb_test #招标范本文件 
    completionName: index_completion_test #搜索补全
  shards: 3
  replicas: 2
  analyzer: hanlp
  
    
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      id-type: auto
      db-type: mysql
    banner: false
    # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: io.gomk.enums
  type-aliases-package: io.gomk.model.entity
    
spring:
  application:
    name: gomk-b-core
  datasource:
    druid:
      min-idle: 10  
      test-while-idle: true
      max-active: 20
      initial-size: 5
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-wait: 10
      url: jdbc:mysql://39.105.192.98:33306/bidata?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&serverTimezone=UTC&useSSL=false
      username: root
      password: Abcd1234!
      #url: jdbc:mysql://58.119.224.27:3306/gomk_test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&serverTimezone=UTC&useSSL=false
      #username: root
      #password: root@2019


swagger:
   host: gomk.io:34568/mb/search
   
hdfs.path: hdfs://localhost:9000
hdfs.username: root
   